// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Traza.Web.Data;

#nullable disable

namespace Traza.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260420165117_EsquemaInicial")]
    partial class EsquemaInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Traza.Web.Data.Entidades.AccionMejora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccionInmediata")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("AccionMejoraPadreId")
                        .HasColumnType("int");

                    b.Property<string>("AnalisisCausas")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("Cerrada")
                        .HasColumnType("bit");

                    b.Property<int?>("CoordinadorId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("EvaluacionCierre")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaObjetivo")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IncidenciaOrigenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificadaEn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrigenId")
                        .HasColumnType("int");

                    b.Property<string>("PlanAccionPropuesto")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("SolicitanteId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoAccionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccionMejoraPadreId");

                    b.HasIndex("CoordinadorId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("IncidenciaOrigenId");

                    b.HasIndex("OrigenId");

                    b.HasIndex("SolicitanteId");

                    b.HasIndex("TipoAccionId");

                    b.ToTable("AccionesMejora", (string)null);
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.AreaProyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("AreasProyecto", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Sin definir"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Arte"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Azentis"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Bodega"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Calidad"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Comercial"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Compras"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Contabilidad"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Control de Stock"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Devoluciones"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Dirección"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Diseño"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Enlace Facturación"
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Estadística"
                        },
                        new
                        {
                            Id = 15,
                            Nombre = "Fábrica"
                        },
                        new
                        {
                            Id = 16,
                            Nombre = "Facturación"
                        },
                        new
                        {
                            Id = 17,
                            Nombre = "Logística"
                        },
                        new
                        {
                            Id = 18,
                            Nombre = "Mantenimiento"
                        },
                        new
                        {
                            Id = 19,
                            Nombre = "Marketing"
                        },
                        new
                        {
                            Id = 20,
                            Nombre = "Producción"
                        },
                        new
                        {
                            Id = 21,
                            Nombre = "Sistemas"
                        },
                        new
                        {
                            Id = 22,
                            Nombre = "Tesorería"
                        });
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.ComentarioAccionMejora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccionMejoraId")
                        .HasColumnType("int");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("EsSeguimiento")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccionMejoraId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ComentariosAccionMejora", (string)null);
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.ComentarioIncidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("EsSeguimiento")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IncidenciaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IncidenciaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ComentariosIncidencia", (string)null);
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.ComentarioProyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("EsSeguimiento")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ComentariosProyecto", (string)null);
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.CosteNoCalidadIncidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IncidenciaId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TipoCosteId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IncidenciaId");

                    b.HasIndex("TipoCosteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CostesNoCalidadIncidencia", (string)null);
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Departamentos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Sistemas"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Calidad"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Producción"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Logística"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Compras"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Comercial"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Mantenimiento"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Administración"
                        });
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.DetalleIncidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClienteProveedor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Codigo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Comentarios")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DocumentoReferencia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<int>("IncidenciaId")
                        .HasColumnType("int");

                    b.Property<string>("Lote")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreIc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Referencia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("IncidenciaId");

                    b.HasIndex("TipoDocumentoId");

                    b.ToTable("DetallesIncidencia", (string)null);
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.DocumentoAccionMejora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccionMejoraId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("FechaDocumento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("RutaArchivo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TipoAdjuntoId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccionMejoraId");

                    b.HasIndex("TipoAdjuntoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("DocumentosAccionMejora", (string)null);
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.DocumentoIncidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("FechaDocumento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IncidenciaId")
                        .HasColumnType("int");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("RutaArchivo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TipoAdjuntoId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IncidenciaId");

                    b.HasIndex("TipoAdjuntoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("DocumentosIncidencia", (string)null);
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.DocumentoProyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("FechaDocumento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<string>("RutaArchivo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TipoAdjuntoId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("TipoAdjuntoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("DocumentosProyecto", (string)null);
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.EstadoAccionMejora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsCierre")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("EstadosAccionMejora", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EsCierre = false,
                            Nombre = "Idea",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            EsCierre = false,
                            Nombre = "En desarrollo",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            EsCierre = false,
                            Nombre = "En revisión",
                            Orden = 3
                        },
                        new
                        {
                            Id = 4,
                            EsCierre = false,
                            Nombre = "Stand by",
                            Orden = 4
                        },
                        new
                        {
                            Id = 5,
                            EsCierre = true,
                            Nombre = "Cancelado",
                            Orden = 5
                        },
                        new
                        {
                            Id = 6,
                            EsCierre = true,
                            Nombre = "Terminado",
                            Orden = 6
                        });
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.EstadoDetalleIncidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("EstadosDetalleIncidencia", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Pendiente",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Aceptado",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Devolución",
                            Orden = 3
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Devolución parcial",
                            Orden = 4
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Destrucción",
                            Orden = 5
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "N/A",
                            Orden = 6
                        });
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.EstadoFaseProyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsCierre")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("EstadosFaseProyecto", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EsCierre = false,
                            Nombre = "Idea",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            EsCierre = false,
                            Nombre = "En desarrollo",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            EsCierre = false,
                            Nombre = "En revisión",
                            Orden = 3
                        },
                        new
                        {
                            Id = 4,
                            EsCierre = false,
                            Nombre = "Stand by",
                            Orden = 4
                        },
                        new
                        {
                            Id = 5,
                            EsCierre = true,
                            Nombre = "Cancelado",
                            Orden = 5
                        },
                        new
                        {
                            Id = 6,
                            EsCierre = true,
                            Nombre = "Terminado",
                            Orden = 6
                        });
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.EstadoIncidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsCierre")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("EstadosIncidencia", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EsCierre = false,
                            Nombre = "Nueva",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            EsCierre = false,
                            Nombre = "En análisis",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            EsCierre = false,
                            Nombre = "En gestión",
                            Orden = 3
                        },
                        new
                        {
                            Id = 4,
                            EsCierre = true,
                            Nombre = "Cerrada",
                            Orden = 4
                        });
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.EstadoProyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsCierre")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("EstadosProyecto", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EsCierre = false,
                            Nombre = "Idea",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            EsCierre = false,
                            Nombre = "En desarrollo",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            EsCierre = false,
                            Nombre = "En revisión",
                            Orden = 3
                        },
                        new
                        {
                            Id = 4,
                            EsCierre = false,
                            Nombre = "Stand by",
                            Orden = 4
                        },
                        new
                        {
                            Id = 5,
                            EsCierre = true,
                            Nombre = "Cancelado",
                            Orden = 5
                        },
                        new
                        {
                            Id = 6,
                            EsCierre = true,
                            Nombre = "Terminado",
                            Orden = 6
                        });
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.FaseProyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaObjetivo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaReal")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<int?>("ResponsableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("ResponsableId");

                    b.ToTable("FasesProyecto", (string)null);
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.Incidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccionCorrectiva")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("AccionInmediata")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("AccionMejoraHijaId")
                        .HasColumnType("int");

                    b.Property<bool>("Cerrada")
                        .HasColumnType("bit");

                    b.Property<int?>("CoordinadorId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("DetectorId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("EvaluacionCierre")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaGestion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("GeneraAccionMejora")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModificadaEn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProcesoId")
                        .HasColumnType("int");

                    b.Property<int?>("TipologiaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccionMejoraHijaId");

                    b.HasIndex("CoordinadorId");

                    b.HasIndex("DetectorId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("ProcesoId");

                    b.HasIndex("TipologiaId");

                    b.ToTable("Incidencias", (string)null);
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.ObjetivoProyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.ToTable("ObjetivosProyecto", (string)null);
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.OrigenAccionMejora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("OrigenesAccionMejora", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Acción de mejora"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Auditoría"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Comité calidad"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Incidencia"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Interna"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Otros"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Preventiva"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Reclamación cliente"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Sugerencias de mejora"
                        });
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.PersonalImplicadoIncidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<int>("IncidenciaId")
                        .HasColumnType("int");

                    b.Property<string>("Notas")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("IncidenciaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PersonalImplicadoIncidencia", (string)null);
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.PresupuestoProyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaEstimacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPresupuesto")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaReal")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ImporteEstimado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ImportePresupuestado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ImporteReal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PresupuestosProyecto", (string)null);
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.PrioridadProyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("PrioridadesProyecto", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Alta",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Media",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Baja",
                            Orden = 3
                        });
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.Proceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Procesos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Administración"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Almacén/Logística"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Comercial"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Compras"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Devoluciones"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Diseño y Desarrollo"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Fabricación contenido"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "SGC"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Control de Calidad"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Mantenimiento"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Planificación en Fábrica"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Producción"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Sistemas"
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "PRL/Seguridad"
                        },
                        new
                        {
                            Id = 15,
                            Nombre = "Quejas de Clientes"
                        },
                        new
                        {
                            Id = 16,
                            Nombre = "Laboratorio/Técnico"
                        },
                        new
                        {
                            Id = 17,
                            Nombre = "Desarrollo de software"
                        },
                        new
                        {
                            Id = 18,
                            Nombre = "Ingeniería"
                        },
                        new
                        {
                            Id = 19,
                            Nombre = "Departamento técnico"
                        },
                        new
                        {
                            Id = 20,
                            Nombre = "Quejas y sugerencias"
                        },
                        new
                        {
                            Id = 21,
                            Nombre = "Sala Blanca"
                        });
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<int?>("CoordinadorId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("PrioridadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("CoordinadorId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("PrioridadId");

                    b.ToTable("Proyectos", (string)null);
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.TareaAccionMejora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccionMejoraId")
                        .HasColumnType("int");

                    b.Property<bool>("Cerrada")
                        .HasColumnType("bit");

                    b.Property<bool>("EsUrgente")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinEsperada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tarea")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("UsuarioAsignadoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccionMejoraId");

                    b.HasIndex("UsuarioAsignadoId");

                    b.ToTable("TareasAccionMejora", (string)null);
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.TareaIncidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cerrada")
                        .HasColumnType("bit");

                    b.Property<bool>("EsUrgente")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinEsperada")
                        .HasColumnType("datetime2");

                    b.Property<int>("IncidenciaId")
                        .HasColumnType("int");

                    b.Property<string>("Tarea")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("UsuarioAsignadoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IncidenciaId");

                    b.HasIndex("UsuarioAsignadoId");

                    b.ToTable("TareasIncidencia", (string)null);
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.TipoAccionMejora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposAccionMejora", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Proyecto de mejora"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Acción correctiva"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Acción preventiva"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Reclamación"
                        });
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.TipoAdjunto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposAdjunto", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Fotografías"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Informe de calidad"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Documento"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Otros"
                        });
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.TipoCosteNoCalidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposCosteNoCalidad", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Recuperado"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Destrucción"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Transporte"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Reproceso"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Cliente"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Otros"
                        });
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.TipoDocumentoReferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposDocumentoReferencia", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "N/A"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Presupuesto"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Pedido"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Albarán"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Factura"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Parte de fabricación"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Preparación de material"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Vale de transporte"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Movimiento entre almacenes"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Packing List"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Vale de entrada almacén"
                        });
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.TipologiaIncidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProcesoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcesoId", "Nombre")
                        .IsUnique();

                    b.ToTable("TipologiasIncidencia", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Nombre = "Sin definir",
                            ProcesoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Nombre = "Sin definir",
                            ProcesoId = 2
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Nombre = "Sin definir",
                            ProcesoId = 3
                        },
                        new
                        {
                            Id = 4,
                            Activa = true,
                            Nombre = "Sin definir",
                            ProcesoId = 4
                        },
                        new
                        {
                            Id = 5,
                            Activa = true,
                            Nombre = "Sin definir",
                            ProcesoId = 5
                        },
                        new
                        {
                            Id = 6,
                            Activa = true,
                            Nombre = "Sin definir",
                            ProcesoId = 6
                        },
                        new
                        {
                            Id = 7,
                            Activa = true,
                            Nombre = "Sin definir",
                            ProcesoId = 7
                        },
                        new
                        {
                            Id = 8,
                            Activa = true,
                            Nombre = "Sin definir",
                            ProcesoId = 8
                        },
                        new
                        {
                            Id = 9,
                            Activa = true,
                            Nombre = "Sin definir",
                            ProcesoId = 9
                        },
                        new
                        {
                            Id = 10,
                            Activa = true,
                            Nombre = "Sin definir",
                            ProcesoId = 10
                        },
                        new
                        {
                            Id = 11,
                            Activa = true,
                            Nombre = "Sin definir",
                            ProcesoId = 11
                        },
                        new
                        {
                            Id = 12,
                            Activa = true,
                            Nombre = "Sin definir",
                            ProcesoId = 12
                        },
                        new
                        {
                            Id = 13,
                            Activa = true,
                            Nombre = "Sin definir",
                            ProcesoId = 13
                        },
                        new
                        {
                            Id = 14,
                            Activa = true,
                            Nombre = "Sin definir",
                            ProcesoId = 14
                        },
                        new
                        {
                            Id = 15,
                            Activa = true,
                            Nombre = "Sin definir",
                            ProcesoId = 15
                        },
                        new
                        {
                            Id = 16,
                            Activa = true,
                            Nombre = "Sin definir",
                            ProcesoId = 16
                        },
                        new
                        {
                            Id = 17,
                            Activa = true,
                            Nombre = "Sin definir",
                            ProcesoId = 17
                        },
                        new
                        {
                            Id = 18,
                            Activa = true,
                            Nombre = "Sin definir",
                            ProcesoId = 18
                        },
                        new
                        {
                            Id = 19,
                            Activa = true,
                            Nombre = "Sin definir",
                            ProcesoId = 19
                        },
                        new
                        {
                            Id = 20,
                            Activa = true,
                            Nombre = "Sin definir",
                            ProcesoId = 20
                        },
                        new
                        {
                            Id = 21,
                            Activa = true,
                            Nombre = "Sin definir",
                            ProcesoId = 21
                        },
                        new
                        {
                            Id = 22,
                            Activa = true,
                            Nombre = "Falta de identificación de mercancía",
                            ProcesoId = 2
                        },
                        new
                        {
                            Id = 23,
                            Activa = true,
                            Nombre = "Error de identificación",
                            ProcesoId = 2
                        },
                        new
                        {
                            Id = 24,
                            Activa = true,
                            Nombre = "Error preparación de pedidos",
                            ProcesoId = 2
                        },
                        new
                        {
                            Id = 25,
                            Activa = true,
                            Nombre = "Error de movimiento de mercancía",
                            ProcesoId = 2
                        },
                        new
                        {
                            Id = 26,
                            Activa = true,
                            Nombre = "Rotura/daño en mercancía",
                            ProcesoId = 2
                        },
                        new
                        {
                            Id = 27,
                            Activa = true,
                            Nombre = "Descuadres de stock",
                            ProcesoId = 2
                        },
                        new
                        {
                            Id = 28,
                            Activa = true,
                            Nombre = "Descuadres detectados en almacenes exteriores durante el arqueo periódico",
                            ProcesoId = 2
                        },
                        new
                        {
                            Id = 29,
                            Activa = true,
                            Nombre = "Desviaciones importantes en inventario",
                            ProcesoId = 2
                        },
                        new
                        {
                            Id = 30,
                            Activa = true,
                            Nombre = "Falta de mercancía",
                            ProcesoId = 2
                        });
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Genero")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("SupervisorId");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            DepartamentoId = 1,
                            Email = "adelgado@traza.local",
                            Login = "adelgado",
                            Nombre = "Alejandro Delgado"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            DepartamentoId = 2,
                            Email = "rtorres@traza.local",
                            Login = "rtorres",
                            Nombre = "Rocío Torres"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            DepartamentoId = 3,
                            Email = "prodriguez@traza.local",
                            Login = "prodriguez",
                            Nombre = "Pablo Rodríguez"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            DepartamentoId = 4,
                            Email = "mpromero@traza.local",
                            Login = "mpromero",
                            Nombre = "Mari Paz Romero"
                        });
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.AccionMejora", b =>
                {
                    b.HasOne("Traza.Web.Data.Entidades.AccionMejora", "AccionMejoraPadre")
                        .WithMany("AccionesHijas")
                        .HasForeignKey("AccionMejoraPadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Traza.Web.Data.Entidades.Usuario", "Coordinador")
                        .WithMany("AccionesMejoraCoordinadas")
                        .HasForeignKey("CoordinadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Traza.Web.Data.Entidades.EstadoAccionMejora", "Estado")
                        .WithMany("Acciones")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Traza.Web.Data.Entidades.Incidencia", "IncidenciaOrigen")
                        .WithMany("AccionesMejoraOrigen")
                        .HasForeignKey("IncidenciaOrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Traza.Web.Data.Entidades.OrigenAccionMejora", "Origen")
                        .WithMany("Acciones")
                        .HasForeignKey("OrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Traza.Web.Data.Entidades.Usuario", "Solicitante")
                        .WithMany("AccionesMejoraSolicitadas")
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Traza.Web.Data.Entidades.TipoAccionMejora", "TipoAccion")
                        .WithMany("Acciones")
                        .HasForeignKey("TipoAccionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AccionMejoraPadre");

                    b.Navigation("Coordinador");

                    b.Navigation("Estado");

                    b.Navigation("IncidenciaOrigen");

                    b.Navigation("Origen");

                    b.Navigation("Solicitante");

                    b.Navigation("TipoAccion");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.ComentarioAccionMejora", b =>
                {
                    b.HasOne("Traza.Web.Data.Entidades.AccionMejora", "AccionMejora")
                        .WithMany("Comentarios")
                        .HasForeignKey("AccionMejoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Traza.Web.Data.Entidades.Usuario", "Usuario")
                        .WithMany("ComentariosAccionMejora")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccionMejora");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.ComentarioIncidencia", b =>
                {
                    b.HasOne("Traza.Web.Data.Entidades.Incidencia", "Incidencia")
                        .WithMany("Comentarios")
                        .HasForeignKey("IncidenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Traza.Web.Data.Entidades.Usuario", "Usuario")
                        .WithMany("ComentariosIncidencia")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Incidencia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.ComentarioProyecto", b =>
                {
                    b.HasOne("Traza.Web.Data.Entidades.Proyecto", "Proyecto")
                        .WithMany("Comentarios")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Traza.Web.Data.Entidades.Usuario", "Usuario")
                        .WithMany("ComentariosProyecto")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.CosteNoCalidadIncidencia", b =>
                {
                    b.HasOne("Traza.Web.Data.Entidades.Incidencia", "Incidencia")
                        .WithMany("CostesNoCalidad")
                        .HasForeignKey("IncidenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Traza.Web.Data.Entidades.TipoCosteNoCalidad", "TipoCoste")
                        .WithMany("Costes")
                        .HasForeignKey("TipoCosteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Traza.Web.Data.Entidades.Usuario", "Usuario")
                        .WithMany("CostesNoCalidad")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Incidencia");

                    b.Navigation("TipoCoste");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.DetalleIncidencia", b =>
                {
                    b.HasOne("Traza.Web.Data.Entidades.EstadoDetalleIncidencia", "Estado")
                        .WithMany("Detalles")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Traza.Web.Data.Entidades.Incidencia", "Incidencia")
                        .WithMany("Detalles")
                        .HasForeignKey("IncidenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Traza.Web.Data.Entidades.TipoDocumentoReferencia", "TipoDocumento")
                        .WithMany("DetallesIncidencia")
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Estado");

                    b.Navigation("Incidencia");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.DocumentoAccionMejora", b =>
                {
                    b.HasOne("Traza.Web.Data.Entidades.AccionMejora", "AccionMejora")
                        .WithMany("Documentos")
                        .HasForeignKey("AccionMejoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Traza.Web.Data.Entidades.TipoAdjunto", "TipoAdjunto")
                        .WithMany("DocumentosAccionMejora")
                        .HasForeignKey("TipoAdjuntoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Traza.Web.Data.Entidades.Usuario", "Usuario")
                        .WithMany("DocumentosAccionMejora")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccionMejora");

                    b.Navigation("TipoAdjunto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.DocumentoIncidencia", b =>
                {
                    b.HasOne("Traza.Web.Data.Entidades.Incidencia", "Incidencia")
                        .WithMany("Documentos")
                        .HasForeignKey("IncidenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Traza.Web.Data.Entidades.TipoAdjunto", "TipoAdjunto")
                        .WithMany("DocumentosIncidencia")
                        .HasForeignKey("TipoAdjuntoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Traza.Web.Data.Entidades.Usuario", "Usuario")
                        .WithMany("DocumentosIncidencia")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Incidencia");

                    b.Navigation("TipoAdjunto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.DocumentoProyecto", b =>
                {
                    b.HasOne("Traza.Web.Data.Entidades.Proyecto", "Proyecto")
                        .WithMany("Documentos")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Traza.Web.Data.Entidades.TipoAdjunto", "TipoAdjunto")
                        .WithMany("DocumentosProyecto")
                        .HasForeignKey("TipoAdjuntoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Traza.Web.Data.Entidades.Usuario", "Usuario")
                        .WithMany("DocumentosProyecto")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("TipoAdjunto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.FaseProyecto", b =>
                {
                    b.HasOne("Traza.Web.Data.Entidades.EstadoFaseProyecto", "Estado")
                        .WithMany("Fases")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Traza.Web.Data.Entidades.Proyecto", "Proyecto")
                        .WithMany("Fases")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Traza.Web.Data.Entidades.Usuario", "Responsable")
                        .WithMany("FasesProyectoResponsable")
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Estado");

                    b.Navigation("Proyecto");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.Incidencia", b =>
                {
                    b.HasOne("Traza.Web.Data.Entidades.AccionMejora", "AccionMejoraHija")
                        .WithMany()
                        .HasForeignKey("AccionMejoraHijaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Traza.Web.Data.Entidades.Usuario", "Coordinador")
                        .WithMany("IncidenciasCoordinadas")
                        .HasForeignKey("CoordinadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Traza.Web.Data.Entidades.Usuario", "Detector")
                        .WithMany("IncidenciasDetectadas")
                        .HasForeignKey("DetectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Traza.Web.Data.Entidades.EstadoIncidencia", "Estado")
                        .WithMany("Incidencias")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Traza.Web.Data.Entidades.Proceso", "Proceso")
                        .WithMany("Incidencias")
                        .HasForeignKey("ProcesoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Traza.Web.Data.Entidades.TipologiaIncidencia", "Tipologia")
                        .WithMany("Incidencias")
                        .HasForeignKey("TipologiaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AccionMejoraHija");

                    b.Navigation("Coordinador");

                    b.Navigation("Detector");

                    b.Navigation("Estado");

                    b.Navigation("Proceso");

                    b.Navigation("Tipologia");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.ObjetivoProyecto", b =>
                {
                    b.HasOne("Traza.Web.Data.Entidades.Proyecto", "Proyecto")
                        .WithMany("Objetivos")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.PersonalImplicadoIncidencia", b =>
                {
                    b.HasOne("Traza.Web.Data.Entidades.Departamento", "Departamento")
                        .WithMany("PersonalImplicado")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Traza.Web.Data.Entidades.Incidencia", "Incidencia")
                        .WithMany("PersonalImplicado")
                        .HasForeignKey("IncidenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Traza.Web.Data.Entidades.Usuario", "Usuario")
                        .WithMany("IncidenciasPersonalImplicado")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");

                    b.Navigation("Incidencia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.PresupuestoProyecto", b =>
                {
                    b.HasOne("Traza.Web.Data.Entidades.Proyecto", "Proyecto")
                        .WithMany("Presupuestos")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Traza.Web.Data.Entidades.Usuario", "Usuario")
                        .WithMany("PresupuestosProyecto")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.Proyecto", b =>
                {
                    b.HasOne("Traza.Web.Data.Entidades.AreaProyecto", "Area")
                        .WithMany("Proyectos")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Traza.Web.Data.Entidades.Usuario", "Coordinador")
                        .WithMany("ProyectosCoordinados")
                        .HasForeignKey("CoordinadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Traza.Web.Data.Entidades.EstadoProyecto", "Estado")
                        .WithMany("Proyectos")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Traza.Web.Data.Entidades.PrioridadProyecto", "Prioridad")
                        .WithMany("Proyectos")
                        .HasForeignKey("PrioridadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Coordinador");

                    b.Navigation("Estado");

                    b.Navigation("Prioridad");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.TareaAccionMejora", b =>
                {
                    b.HasOne("Traza.Web.Data.Entidades.AccionMejora", "AccionMejora")
                        .WithMany("Tareas")
                        .HasForeignKey("AccionMejoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Traza.Web.Data.Entidades.Usuario", "UsuarioAsignado")
                        .WithMany("TareasAccionMejora")
                        .HasForeignKey("UsuarioAsignadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccionMejora");

                    b.Navigation("UsuarioAsignado");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.TareaIncidencia", b =>
                {
                    b.HasOne("Traza.Web.Data.Entidades.Incidencia", "Incidencia")
                        .WithMany("Tareas")
                        .HasForeignKey("IncidenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Traza.Web.Data.Entidades.Usuario", "UsuarioAsignado")
                        .WithMany("TareasIncidencia")
                        .HasForeignKey("UsuarioAsignadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Incidencia");

                    b.Navigation("UsuarioAsignado");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.TipologiaIncidencia", b =>
                {
                    b.HasOne("Traza.Web.Data.Entidades.Proceso", "Proceso")
                        .WithMany("Tipologias")
                        .HasForeignKey("ProcesoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proceso");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.Usuario", b =>
                {
                    b.HasOne("Traza.Web.Data.Entidades.Departamento", "Departamento")
                        .WithMany("Usuarios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Traza.Web.Data.Entidades.Usuario", "Supervisor")
                        .WithMany("Colaboradores")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Departamento");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.AccionMejora", b =>
                {
                    b.Navigation("AccionesHijas");

                    b.Navigation("Comentarios");

                    b.Navigation("Documentos");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.AreaProyecto", b =>
                {
                    b.Navigation("Proyectos");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.Departamento", b =>
                {
                    b.Navigation("PersonalImplicado");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.EstadoAccionMejora", b =>
                {
                    b.Navigation("Acciones");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.EstadoDetalleIncidencia", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.EstadoFaseProyecto", b =>
                {
                    b.Navigation("Fases");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.EstadoIncidencia", b =>
                {
                    b.Navigation("Incidencias");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.EstadoProyecto", b =>
                {
                    b.Navigation("Proyectos");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.Incidencia", b =>
                {
                    b.Navigation("AccionesMejoraOrigen");

                    b.Navigation("Comentarios");

                    b.Navigation("CostesNoCalidad");

                    b.Navigation("Detalles");

                    b.Navigation("Documentos");

                    b.Navigation("PersonalImplicado");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.OrigenAccionMejora", b =>
                {
                    b.Navigation("Acciones");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.PrioridadProyecto", b =>
                {
                    b.Navigation("Proyectos");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.Proceso", b =>
                {
                    b.Navigation("Incidencias");

                    b.Navigation("Tipologias");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.Proyecto", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Documentos");

                    b.Navigation("Fases");

                    b.Navigation("Objetivos");

                    b.Navigation("Presupuestos");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.TipoAccionMejora", b =>
                {
                    b.Navigation("Acciones");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.TipoAdjunto", b =>
                {
                    b.Navigation("DocumentosAccionMejora");

                    b.Navigation("DocumentosIncidencia");

                    b.Navigation("DocumentosProyecto");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.TipoCosteNoCalidad", b =>
                {
                    b.Navigation("Costes");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.TipoDocumentoReferencia", b =>
                {
                    b.Navigation("DetallesIncidencia");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.TipologiaIncidencia", b =>
                {
                    b.Navigation("Incidencias");
                });

            modelBuilder.Entity("Traza.Web.Data.Entidades.Usuario", b =>
                {
                    b.Navigation("AccionesMejoraCoordinadas");

                    b.Navigation("AccionesMejoraSolicitadas");

                    b.Navigation("Colaboradores");

                    b.Navigation("ComentariosAccionMejora");

                    b.Navigation("ComentariosIncidencia");

                    b.Navigation("ComentariosProyecto");

                    b.Navigation("CostesNoCalidad");

                    b.Navigation("DocumentosAccionMejora");

                    b.Navigation("DocumentosIncidencia");

                    b.Navigation("DocumentosProyecto");

                    b.Navigation("FasesProyectoResponsable");

                    b.Navigation("IncidenciasCoordinadas");

                    b.Navigation("IncidenciasDetectadas");

                    b.Navigation("IncidenciasPersonalImplicado");

                    b.Navigation("PresupuestosProyecto");

                    b.Navigation("ProyectosCoordinados");

                    b.Navigation("TareasAccionMejora");

                    b.Navigation("TareasIncidencia");
                });
#pragma warning restore 612, 618
        }
    }
}
